# Selecionados 3 textos para teste e definida a Lista Verdade, para avaliação dos resultados

In [118]:
set_verdade = set({'ETL','Office','SQL','Python','R','Go','Power BI','Pentaho','Tableau','Apache NiFi','Talend','Glue','Airflow','SQL Server','PostgreSQL','Looker','Pandas','Scikit-learn','Machine Learning','Data Warehouses','Data Lakes', 'Azure', 'AWS', 'Databricks', 'Spark', 'Azure Data Factory', 'Azure Event Hubs', 'NoSQL', 'DevOps', 'Java', 'Scala', 'Dynatrace', 'Splunk', 'ELK', 'Grafana', 'OpenTelemetry', 'algoritmos', 'backend java', 'business intelligence','PL-330'})

descricao_vaga_portugues_orig = [
    "Para agregar nosso time, suas principais atividades a serem exercidas serão:  Executar atividades de extração, transformação e carregamento (ETL) de dados, assegurando a integridade e precisão das informações processadas. Desenvolver e manter dashboards interativos para visualização e análise de dados, adaptando-os às necessidades dos stakeholders. Criar e monitorar indicadores-chave de performance (KPIs). Automatizar processos para melhorar a eficiência e reduzir erros. Realizar análises estatísticas para gerar insights que apoiem a tomada de decisões e contribuir com valores incrementais. Garantir a entrega dos projetos dentro dos prazos estipulados, mantendo padrões de qualidade e otimizando recursos técnicos e materiais. Colaborar com stakeholders para entender e atender às suas necessidades, promovendo a melhoria contínua dos processos, assegurando a entrega de relatórios e apresentações gerenciais sobre os resultados e progresso dos projetos.  Vamos adorar caso você possa contribuir com as seguintes competências: Superior em alguns dos cursos: Engenharia da Computação, Sistemas da Informação, Inteligência de Negócio, Estatística ou áreas correlatas;  Experiência sólida nas seguintes ferramentas: SQL, Python, Power BI e Pentaho; Pacote office completo; Conhecimento em ETL; Inglês intermediário; Capacidade de adaptação.",
    "Projetar, construir e manter pipelines de dados robustos e escaláveis;- Desenvolver e gerenciar processos de ETL para integrar dados de múltiplas fontes em data warehouses e data lakes;- Colaborar com equipes de negócios e TI para definir e entender requisitos de dados e relatórios;- Criar dashboards e relatórios interativos usando ferramentas de BI (como Power BI, Tableau, etc.) para suportar a tomada de decisão;- Analisar grandes conjuntos de dados para identificar tendências, padrões e insights estratégicos;- Garantir a qualidade dos dados e a governança de dados através de práticas rigorosas de monitoramento e validação. - Superior Completo em Ciência da Computação, Engenharia de Dados, Análise de Dados ou áreas relacionadas;- Sólida experiência em SQL e outras linguagens de consulta e manipulação de dados;- Conhecimento avançado em ferramentas de ETL (como Apache NiFi, Talend, Glue, Airflow);- Experiência com sistemas de banco de dados relacional (SQL Server, PostgreSQL, etc.);- Familiaridade com ferramentas de BI (Power BI, Tableau, Looker, etc.) e linguagens de programação (Python, Go);- Habilidade comprovada na criação de relatórios e visualizações de dados que comunicam insights de forma clara e eficaz;- Experiência com arquitetura de data lakes e data warehouses;- Excelentes habilidades de comunicação e colaboração;- Proatividade e capacidade de resolver problemas complexos de maneira criativa",
    "Ciência de Dados  para  a Gerência Executiva, profissional  STEM (Science, Technology, Engineering, and Mathematics) - com a responsabilidade de suportar os  processos;Planejamento e Controle e Riscos  Operacionais  e de reporte à liderança Executiva;Suporte aos  processos  de Planejamento e Controle e Riscos  Operacionais, utilizando métodos quantitativos  de análise de dados  avançadas;Promover o avanço das  análise de dados  de forma  descritiva, para preditiva e,especialmente, prescritiva. As  análises  devem considerar os  diversos  KPI da árvore de valor das unidades  de negócio. experiência em análise de dados/business  analysts  e ciência de dados; ou logística, supply chain management e gestão de frotas  (schedulling); ou controle da  produção de óleo e gás; ou gestão de grandes  projetos  de engenharia; ou planejamento e controle (PCP).Sólida  experiência em ciência de dados, incluindo advanced analytics, modelos  preditivos  e prescritivos, clusterização machine learning  e otimização; Profissional certificado em POWER BI pela Microsoft 70-778, PL-330, 70-799 ou equivalente;Programação avançada em Python/R (incluindo pacotes  open-source - Pandas, Scikit-learn, etc.); Desejável conhecimento em SQL para consulta de base de dados  e geração de análises;Conhecimentos  e habilidades  em algoritmos  e estruturas  de dados;Nivel Superior em Engenharia, Com registro regular no respectivo conselho de classe.",
    "Requisitos e qualificações. Pra mandar bem nessa oportunidade você precisa manjar das tecnologias:(Conhecimentos técnicos obrigatórios) Experiência com desenvolvimento na nuvem (Azure e/ou AWS), com conhecimento depráticas para otimização de custos; Vasta experiência em engenharia de dados e data lake, com foco na construção depipelines de dados escaláveis utilizando Databricks e Spark; Excelentes noções de arquitetura e system design, sabendo lidar com grandes volumes de dados em batch e real time; Conhecimento avançado em ferramentas de dados como o Azure Data Factory (ou equivalentes) e Azure Event Hubs (ou equivalentes); Experiência com bancos de dados relacionais e bancos de dados NoSQL; Experiência com ferramentas de DevOps, CI/CD; Conhecimento avançado em Java e/ou Scala para pipelines de manipulação de dados; Conhecimento profundo de SQL; Conhecimento em testes unitários e automatizados; e Experiência de implantação de mecanismos de observabilidade de dados. Vai ser bom se você também tiver:(Conhecimentos técnicos desejáveis, que serão um diferencial)Conhecimento de práticas e ferramentas do BI tradicional; Conhecimentos em Dynatrace, Splunk, ELK, Grafana, OpenTelemetry; e Conhecimentos de Backend Java. O que não abrimos mão:(Soft Skills) Colaboração; Proatividade; e Trabalho em equipe.Informações adicionais Para esta posição oferecemos: Salário CLT Full; Vale Refeição ou Alimentação (Alelo); Vale Transporte (sempre que houver o deslocamento); Auxílio Home Office (proporcional aos dias em que atuará nesta modalidade); Assistência Médica Sulamérica; Assistência Odontológica Sulamérica; Seguro de Vida; Parcerias (Curso de idiomas, ensino, livraria, restaurante, entre outras); Gympass; Allya; Day Off; Premiação por indicações; Inside Out (Ocorre todas as quartas-feiras. Evento da galera voltado para troca deconhecimento); Oportunidade de crescimento profissional. Etapas do processo; A Solutis é Digital! Somos apaixonados por tecnologia e esse valor está presente em nossas ações e proposta de trabalho. Ambiente descontraído e criativo, horário flexível, possibilidade de trabalho home office, eventos e programas internos com games... Isso faz parte do nosso dia-a-dia. Engajamento, busca intensa por conhecimento, empatia e criatividade são a nossa receita para cultivar e colher, sempre, o melhor resultado tecnológico. Essa é a Solutis, flexível, acolhedora, inquieta, amante da tecnologia e de tudo que ela nos proporciona de mais incrível. Venha fazer parte do nosso time!"
    ]

descricao_vaga_ingles_orig = [
    "To enhance our team, your main activities will include: Executing data extraction, transformation, and loading (ETL) activities, ensuring the integrity and accuracy of the processed information. Developing and maintaining interactive dashboards for data visualization and analysis, adapting them to the needs of stakeholders. Creating and monitoring key performance indicators (KPIs). Automating processes to improve efficiency and reduce errors. Conducting statistical analyses to generate insights that support decision-making and contribute incremental value. Ensuring the delivery of projects within the stipulated deadlines, maintaining quality standards, and optimizing technical and material resources. Collaborating with stakeholders to understand and meet their needs, promoting continuous improvement of processes, ensuring the delivery of reports and management presentations on project results and progress. We would love it if you could contribute with the following skills: A degree in some of the following fields: Computer Engineering, Information Systems, Business Intelligence, Statistics, or related areas; Solid experience with the following tools: SQL, Python, Power BI, and Pentaho; Complete Office package; Knowledge in ETL; Intermediate English; Adaptability.",
    "Design, build, and maintain robust and scalable data pipelines; - Develop and manage ETL processes to integrate data from multiple sources into data warehouses and data lakes; - Collaborate with business and IT teams to define and understand data and reporting requirements; - Create dashboards and interactive reports using BI tools (such as Power BI, Tableau, etc.) to support decision-making; - Analyze large datasets to identify trends, patterns, and strategic insights; - Ensure data quality and data governance through rigorous monitoring and validation practices. - Bachelor's degree in Computer Science, Data Engineering, Data Analysis, or related fields; - Solid experience in SQL and other data query and manipulation languages; - Advanced knowledge of ETL tools (such as Apache NiFi, Talend, Glue, Airflow); - Experience with relational database systems (SQL Server, PostgreSQL, etc.); - Familiarity with BI tools (Power BI, Tableau, Looker, etc.) and programming languages (Python, Go); - Proven ability to create reports and data visualizations that communicate insights clearly and effectively; - Experience with data lake and data warehouse architecture; - Excellent communication and collaboration skills; - Proactivity and ability to solve complex problems creatively.",
    "Data Science for Executive Management, STEM (Science, Technology, Engineering, and Mathematics) professional - responsible for supporting processes; Planning and Control and Operational Risks and reporting to Executive leadership; Support for Planning and Control and Operational Risks processes, using quantitative methods for advanced data analysis; Promote the advancement of data analysis from descriptive to predictive and especially prescriptive. The analyses must consider the various KPIs of the value tree of the business units. Experience in data analysis/business analysis and data science; or logistics, supply chain management, and fleet management (scheduling); or oil and gas production control; or management of large engineering projects; or planning and control (PCP). Solid experience in data science, including advanced analytics, predictive and prescriptive models, clustering, machine learning, and optimization; Certified professional in POWER BI by Microsoft 70-778, PL-330, 70-799, or equivalent; Advanced programming in Python/R (including open-source packages - Pandas, Scikit-learn, etc.); Desirable knowledge in SQL for database querying and analysis generation; Knowledge and skills in algorithms and data structures; Higher education in Engineering, with regular registration in the respective professional council.",
    "Requirements and qualificationsTo succeed in this opportunity, you need to be a technology proficient: (Required technical knowledge) Experience with cloud development (Azure and/or AWS), with knowledge of practices for cost optimization; Extensive experience in data engineering and data lake, with a focus on building scalable data pipelines using Databricks and Spark; Excellent knowledge of architecture and system design, knowing how to handle large volumes of data in batch and real time; Advanced knowledge of data tools such as Azure Data Factory (or equivalent) and Azure Event Hubs (or equivalent); Experience with relational databases and NoSQL databases; Experience with DevOps, CI/CD tools; Advanced knowledge of Java and/or Scala for data manipulation pipelines; Deep knowledge of SQL; Knowledge of unit and automated testing; and Experience in implementing data observability mechanisms. It will be good if you also have: (Desirable technical knowledge, which will be a differential) Knowledge of traditional BI practices and tools; Knowledge of Dynatrace, Splunk, ELK, Grafana, OpenTelemetry; and Knowledge of Java Backend What we do not give up: (Soft Skills) Collaboration; Proactivity; and Teamwork. Additional informationFor this position we offer:Full CLT Salary;Meal or Food Voucher (Alelo);Transportation Voucher (whenever there is a commute);Home Office Assistance (proportional to the days in which you will work in this modality);Sulamérica Medical Assistance;Sulamérica Dental Assistance;Life Insurance;Partnerships (Language course, teaching, bookstore, restaurant, among others);Gympass;Allya;Day Off;Referral Awards;Inside Out (Occurs every Wednesday. Event for the group focused on exchanging knowledge);Opportunity for professional growth.Process stagesSolutis is Digital!We are passionate about technology and this value is present in our actions and work proposal. A relaxed and creative environment, flexible hours, the possibility of working from home, events and internal programs with games... This is part of our daily routine. Engagement, an intense search for knowledge, empathy and creativity are our recipe for always cultivating and harvesting the best technological results. This is Solutis, flexible, welcoming, restless, a lover of technology and everything incredible that it provides us. Come be part of our team!"]

# transformando tudo em maiúsculo
# descricao_vaga_portugues = descricao_vaga_portugues.upper()
# descricao_vaga_ingles = descricao_vaga_ingles.upper()

In [29]:
def pre_tratamento_pontuacao(descricao_vaga):
    descricao_vaga = descricao_vaga.replace(";", ", ")
    descricao_vaga = descricao_vaga.replace("(", ", ")
    descricao_vaga = descricao_vaga.replace("),", ", ")
    descricao_vaga = descricao_vaga.replace(")", ", ")
    descricao_vaga = descricao_vaga.replace("/", ", ")
    descricao_vaga = descricao_vaga.replace(".", ". ")
    descricao_vaga = descricao_vaga.replace("|", ", ")
    descricao_vaga = descricao_vaga.replace(",", ", ")
    descricao_vaga = descricao_vaga.replace(",,", ", ")
    descricao_vaga = descricao_vaga.replace("  ", " ")
    descricao_vaga = descricao_vaga.replace(",, ", ", ")
    descricao_vaga = descricao_vaga.replace(", .", ".")
    descricao_vaga = descricao_vaga.replace(". ,", ".")

    return descricao_vaga

def tratar_lista(lst_resp):
    #splitar a lista de software
    lst_sw = [item.replace(" and ", ",").replace(" e ", ",").replace(", ", ",") for item in lst_resp]
    lst_sw = [item.split(",") for item in lst_sw]

    #trasnformar a lista em um conjunto
    set_sw = set()
    for item in lst_sw:
        set_sw.update(item)
    
    return set_sw

In [30]:
descricao_vaga_portugues = []
descricao_vaga_ingles = []


for i in descricao_vaga_portugues_orig:
    descricao_vaga_portugues.append(pre_tratamento_pontuacao(i))

for i in descricao_vaga_ingles_orig:
    descricao_vaga_ingles.append(pre_tratamento_pontuacao(i))

In [31]:
print(descricao_vaga_portugues)

['Para agregar nosso time, suas principais atividades a serem exercidas serão: Executar atividades de extração, transformação e carregamento , ETL,  de dados, assegurando a integridade e precisão das informações processadas. Desenvolver e manter dashboards interativos para visualização e análise de dados, adaptando-os às necessidades dos stakeholders. Criar e monitorar indicadores-chave de performance , KPIs. Automatizar processos para melhorar a eficiência e reduzir erros. Realizar análises estatísticas para gerar insights que apoiem a tomada de decisões e contribuir com valores incrementais. Garantir a entrega dos projetos dentro dos prazos estipulados, mantendo padrões de qualidade e otimizando recursos técnicos e materiais. Colaborar com stakeholders para entender e atender às suas necessidades, promovendo a melhoria contínua dos processos, assegurando a entrega de relatórios e apresentações gerenciais sobre os resultados e progresso dos projetos.  Vamos adorar caso você possa contribuir com as seguintes competências: Superior em alguns dos cursos: Engenharia da Computação, Sistemas da Informação, Inteligência de Negócio, Estatística ou áreas correlatas,  Experiência sólida nas seguintes ferramentas: SQL, Python, Power BI e Pentaho,  Pacote office completo,  Conhecimento em ETL,  Inglês intermediário,  Capacidade de adaptação. ', 'Projetar, construir e manter pipelines de dados robustos e escaláveis, - Desenvolver e gerenciar processos de ETL para integrar dados de múltiplas fontes em data warehouses e data lakes, - Colaborar com equipes de negócios e TI para definir e entender requisitos de dados e relatórios, - Criar dashboards e relatórios interativos usando ferramentas de BI , como Power BI, Tableau, etc.  para suportar a tomada de decisão, - Analisar grandes conjuntos de dados para identificar tendências, padrões e insights estratégicos, - Garantir a qualidade dos dados e a governança de dados através de práticas rigorosas de monitoramento e validação. - Superior Completo em Ciência da Computação, Engenharia de Dados, Análise de Dados ou áreas relacionadas, - Sólida experiência em SQL e outras linguagens de consulta e manipulação de dados, - Conhecimento avançado em ferramentas de ETL , como Apache NiFi, Talend, Glue, Airflow,  - Experiência com sistemas de banco de dados relacional , SQL Server, PostgreSQL, etc.  - Familiaridade com ferramentas de BI , Power BI, Tableau, Looker, etc.  e linguagens de programação , Python, Go,  - Habilidade comprovada na criação de relatórios e visualizações de dados que comunicam insights de forma clara e eficaz, - Experiência com arquitetura de data lakes e data warehouses, - Excelentes habilidades de comunicação e colaboração, - Proatividade e capacidade de resolver problemas complexos de maneira criativa', 'Ciência de Dados para a Gerência Executiva, profissional STEM , Science, Technology, Engineering, and Mathematics,  - com a responsabilidade de suportar os processos, Planejamento e Controle e Riscos Operacionais e de reporte à liderança Executiva, Suporte aos processos de Planejamento e Controle e Riscos Operacionais, utilizando métodos quantitativos de análise de dados avançadas, Promover o avanço das análise de dados de forma descritiva, para preditiva e, especialmente, prescritiva. As análises devem considerar os diversos KPI da árvore de valor das unidades de negócio. experiência em análise de dados, business analysts e ciência de dados,  ou logística, supply chain management e gestão de frotas , schedulling,  ou controle da produção de óleo e gás,  ou gestão de grandes projetos de engenharia,  ou planejamento e controle , PCP. Sólida experiência em ciência de dados, incluindo advanced analytics, modelos preditivos e prescritivos, clusterização machine learning e otimização,  Profissional certificado em POWER BI pela Microsoft 70-778, PL-330, 70-799 ou equivalente, Programação avançada em Python, R , incluindo pacotes open-source - Pandas, Sckit-learn, etc.  Desejável conhecimento em SQL para consulta de base de dados e geração de análises, Conhecimentos e habilidades em algoritmos e estruturas de dados, Nivel Superior em Engenharia, Com registro regular no respectivo conselho de classe. ', 'Requisitos e qualificações. Pra mandar bem nessa oportunidade você precisa manjar das tecnologias:, Conhecimentos técnicos obrigatórios,  Experiência com desenvolvimento na nuvem , Azure e, ou AWS,  com conhecimento depráticas para otimização de custos,  Vasta experiência em engenharia de dados e data lake, com foco na construção depipelines de dados escaláveis utilizando Databricks e Spark,  Excelentes noções de arquitetura e system design, sabendo lidar com grandes volumes de dados em batch e real time,  Conhecimento avançado em ferramentas de dados como o Azure Data Factory , ou equivalentes,  e Azure Event Hubs , ou equivalentes,  Experiência com bancos de dados relacionais e bancos de dados NoSQL,  Experiência com ferramentas de DevOps, CI, CD,  Conhecimento avançado em Java e, ou Scala para pipelines de manipulação de dados,  Conhecimento profundo de SQL,  Conhecimento em testes unitários e automatizados,  e Experiência de implantação de mecanismos de observabilidade de dados. Vai ser bom se você também tiver:, Conhecimentos técnicos desejáveis, que serão um diferencial, Conhecimento de práticas e ferramentas do BI tradicional,  Conhecimentos em Dynatrace, Splunk, ELK, Grafana, OpenTelemetry,  e Conhecimentos de Backend Java. O que não abrimos mão:, Soft Skills,  Colaboração,  Proatividade,  e Trabalho em equipe. Informações adicionais Para esta posição oferecemos: Salário CLT Full,  Vale Refeição ou Alimentação , Alelo,  Vale Transporte , sempre que houver o deslocamento,  Auxílio Home Office , proporcional aos dias em que atuará nesta modalidade,  Assistência Médica Sulamérica,  Assistência Odontológica Sulamérica,  Seguro de Vida,  Parcerias , Curso de idiomas, ensino, livraria, restaurante, entre outras,  Gympass,  Allya,  Day Off,  Premiação por indicações,  Inside Out , Ocorre todas as quartas-feiras. Evento da galera voltado para troca deconhecimento,  Oportunidade de crescimento profissional. Etapas do processo,  A Solutis é Digital! Somos apaixonados por tecnologia e esse valor está presente em nossas ações e proposta de trabalho. Ambiente descontraído e criativo, horário flexível, possibilidade de trabalho home office, eventos e programas internos com games. . . Isso faz parte do nosso dia-a-dia. Engajamento, busca intensa por conhecimento, empatia e criatividade são a nossa receita para cultivar e colher, sempre, o melhor resultado tecnológico. Essa é a Solutis, flexível, acolhedora, inquieta, amante da tecnologia e de tudo que ela nos proporciona de mais incrível. Venha fazer parte do nosso time!']

# Teste 1 - Modelo Tiny Roberta - Em Inglês

#### O modelo de QA Tiny Roberta só retorna a primeira sequência dentro do texto. Ou seja, se os softwares forem citados em frases distintas o modelo só irá retornar a primeira ocorrência.

In [32]:
from transformers import pipeline

pipe = pipeline("question-answering", model="deepset/tinyroberta-squad2")

prompt = "Which software names are mentioned in the text?"
lst_resp = []

for vaga in descricao_vaga_ingles:
    resposta = pipe(question = prompt, context = vaga)
    lst_resp.append(resposta['answer'])

set_sw_TinyBerta = tratar_lista(lst_resp)
set_sw_TinyBerta

{'',
 ' Collaboration',
 ' Proactivity',
 'Go',
 'Pandas',
 'Pentaho',
 'Power BI',
 'Python',
 'SQL',
 'Scikit-learn',
 'Skills',
 'Teamwork'}

# Teste 2 - Modelo Bert - Fining Tuning em Português

#### O modelo de QA Bert PT retornou o mesmo resultado do Tiny Roberta, dispensando a tradução do contexto para inglês.

In [33]:
pipe = pipeline("question-answering", model="pierreguillou/bert-base-cased-squad-v1.1-portuguese")

prompt = "Quais Softwares são mencionados no texto?"
lst_resp = []

for vaga in descricao_vaga_portugues:
    resposta = pipe(question = prompt, context = vaga)
    lst_resp.append(resposta['answer'])

set_sw_BertPT = tratar_lista(lst_resp)
set_sw_BertPT

{'Azure e', 'Go', 'Pandas', 'Pentaho', 'Power BI', 'Python', 'SQL', 'ou AWS'}

# Teste 3 - Modelo Bert - Fining Tuning em Português
### Abordagem passando uma frase por vez
#### Nesta abordagem, mesmo que não exista uma resposta na frase o modelo retorna algo, trazendo uma grande quantidade de falsos positivos. Para melhorar, fiz um filtro no Score baixo, removendo boa parte dos falsos positivos.

In [34]:
from transformers import pipeline
import pandas as pd

pipe = pipeline("question-answering", model="pierreguillou/bert-base-cased-squad-v1.1-portuguese")

prompt = "Quais Softwares são mencionados no texto?"
lst_resp = []

for vaga in descricao_vaga_portugues:
    lista_frases = vaga.split(".")
    for frase in lista_frases:
        if frase:
            resposta = pipe(question = prompt, context = frase)
            lst_resp.append(resposta)

#converter o valor de científico para float
df = pd.DataFrame(lst_resp)

#arredondar o score e filtrar o score
df['score'] = df['score'].apply(lambda x: round(x, 6))
df.sort_values(by='score', ascending=False, inplace=True)
df

       score  start  end                                             answer
27  0.805071    102  130                       programas internos com games
21  0.796320    154  169                                    Azure e, ou AWS
12  0.756839     37   67                     BI , Power BI, Tableau, Looker
7   0.705024    259  290                    SQL, Python, Power BI e Pentaho
22  0.621864    224  253                      Conhecimentos de Backend Java
0   0.420259    141  155                                     ETL,  de dados
24  0.261691    405  412                                            Gympass
1   0.207154     22   32                                         dashboards
9   0.175511    362  379                                  Power BI, Tableau
18  0.161255    117  149                   algoritmos e estruturas de dados
23  0.076154     25   36                                        Soft Skills
25  0.061306     54   94           Oportunidade de crescimento profissional
15  0.060392     42   45                                                KPI
2   0.054655     54   58                                               KPIs
17  0.026190    311  330                                Pandas, Sckit-learn
31  0.019482     14   68  busca intensa por conhecimento, empatia e cria...
11  0.013919    340  362                             SQL Server, PostgreSQL
13  0.000482     32   42                                         Python, Go
33  0.000479      1   33                   Venha fazer parte do nosso time!
26  0.000315     34   41                                            Digital
32  0.000243     10   17                                            Solutis
16  0.000122    261  264                                                PCP
20  0.000057      0   10                                         Requisitos
30  0.000047     10   15                                              parte
3   0.000033      1   65  Automatizar processos para melhorar a eficiênc...
5   0.000016     64  136  mantendo padrões de qualidade e otimizando rec...
6   0.000010    219  227                                           projetos
14  0.000005     57   61                                               STEM
4   0.000002      1   31                     Realizar análises estatísticas
8   0.000000      0    0
10  0.000000      7   35                       suportar a tomada de decisão
19  0.000000      0    0
29  0.000000      0    0
28  0.000000      0    0

In [35]:
#Filtrando o score
df = df[df['score'] > 0.001]

#transformar a coluna answer em uma lista
lista_software = df['answer'].to_list()

set_sw_BertPT_V2 = tratar_lista(lista_software)

set_sw_BertPT_V2

{' de dados',
 'Azure e',
 'BI ',
 'Conhecimentos de Backend Java',
 'ETL',
 'Gympass',
 'KPI',
 'KPIs',
 'Looker',
 'Oportunidade de crescimento profissional',
 'Pandas',
 'Pentaho',
 'PostgreSQL',
 'Power BI',
 'Python',
 'SQL',
 'SQL Server',
 'Sckit-learn',
 'Soft Skills',
 'Tableau',
 'algoritmos',
 'busca intensa por conhecimento',
 'criatividade',
 'dashboards',
 'empatia',
 'estruturas de dados',
 'ou AWS',
 'programas internos com games'}

# Teste 4 - Spacy em Inglês
### Modelo NLP de Extração de Entidades Nomeadas (NER)

#### Nesta abordagem a maior parte das entidades que desejo estão classificadas como ORG

In [36]:
#!python -m spacy download en_core_web_lg

^C

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ---------------------------------------- 0.0/400.7 MB ? eta -:--:--
     ---------------------------------------- 0.5/400.7 MB 3.4 MB/s eta 0:02:00
     ---------------------------------------- 1.6/400.7 MB 4.0 MB/s eta 0:01:40
     ---------------------------------------- 2.6/400.7 MB 4.6 MB/s eta 0:01:28
     ---------------------------------------- 3.7/400.7 MB 4.7 MB/s eta 0:01:24
     ---------------------------------------- 4.7/400.7 MB 4.9 MB/s eta 0:01:21
      --------------------------------------- 5.8/400.7 MB 4.8 MB/s eta 0:01:22
      --------------------------------------- 6.8/400.7 MB 4.9 MB/s eta 0:01:20
      --------------------------------------- 7.9/400.7 MB 4.9 MB/s eta 0:01:20
      --------------------------------------- 9.2/400.7 MB 5.1 MB/s eta 0:01:17
      -------------------------------------- 10.2/400.7 MB 5.1 MB/s eta 0:01:18
     - ------------------------------------- 10.7/400.7 MB 4.9 MB/s eta 0:01:21
     - ------------------------------------- 11.8/400.7 MB 4.9 MB/s eta 0:01:21
     - ------------------------------------- 13.1/400.7 MB 5.0 MB/s eta 0:01:18
     - ------------------------------------- 14.4/400.7 MB 5.0 MB/s eta 0:01:17
     - ------------------------------------- 15.5/400.7 MB 5.0 MB/s eta 0:01:17
     - ------------------------------------- 16.8/400.7 MB 5.1 MB/s eta 0:01:16
     - ------------------------------------- 18.1/400.7 MB 5.2 MB/s eta 0:01:15
     - ------------------------------------- 18.4/400.7 MB 5.0 MB/s eta 0:01:17
     - ------------------------------------- 18.6/400.7 MB 4.9 MB/s eta 0:01:19
     - ------------------------------------- 18.9/400.7 MB 4.6 MB/s eta 0:01:23
     - ------------------------------------- 19.1/400.7 MB 4.5 MB/s eta 0:01:25
     - ------------------------------------- 19.4/400.7 MB 4.4 MB/s eta 0:01:27
     - ------------------------------------- 19.7/400.7 MB 4.2 MB/s eta 0:01:30
     - ------------------------------------- 19.9/400.7 MB 4.1 MB/s eta 0:01:33
     - ------------------------------------- 20.2/400.7 MB 4.0 MB/s eta 0:01:36
     - ------------------------------------- 20.4/400.7 MB 3.9 MB/s eta 0:01:39
     -- ------------------------------------ 21.0/400.7 MB 3.7 MB/s eta 0:01:43
     -- ------------------------------------ 21.2/400.7 MB 3.7 MB/s eta 0:01:43
     -- ------------------------------------ 21.8/400.7 MB 3.6 MB/s eta 0:01:46
     -- ------------------------------------ 22.3/400.7 MB 3.5 MB/s eta 0:01:47
     -- ------------------------------------ 22.8/400.7 MB 3.5 MB/s eta 0:01:48
     -- ------------------------------------ 23.6/400.7 MB 3.5 MB/s eta 0:01:48
     -- ------------------------------------ 24.4/400.7 MB 3.5 MB/s eta 0:01:47
     -- ------------------------------------ 26.0/400.7 MB 3.6 MB/s eta 0:01:43
     -- ------------------------------------ 27.5/400.7 MB 3.8 MB/s eta 0:01:40
     -- ------------------------------------ 29.1/400.7 MB 3.9 MB/s eta 0:01:37
     --- ----------------------------------- 31.2/400.7 MB 4.0 MB/s eta 0:01:33
     --- ----------------------------------- 32.8/400.7 MB 4.1 MB/s eta 0:01:30
     --- ----------------------------------- 34.3/400.7 MB 4.2 MB/s eta 0:01:28
     --- ----------------------------------- 36.2/400.7 MB 4.3 MB/s eta 0:01:25
     --- ----------------------------------- 38.0/400.7 MB 4.4 MB/s eta 0:01:23
     --- ----------------------------------- 39.8/400.7 MB 4.5 MB/s eta 0:01:20
     ---- ---------------------------------- 41.4/400.7 MB 4.6 MB/s eta 0:01:19
     ---- ---------------------------------- 43.3/400.7 MB 4.7 MB/s eta 0:01:17
     ---- ---------------------------------- 44.8/400.7 MB 4.8 MB/s eta 0:01:15
     ---- ---------------------------------- 46.9/400.7 MB 4.9 MB/s eta 0:01:13
     ---- ---------------------------------- 48.8/400.7 MB 4.9 MB/s eta 0:01:12
     ---- ---------------------------------- 50.6/400.7 MB 5.0 MB/s eta 0:01:10
     ----- --------------------------------- 52.4/400.7 MB 5.1 MB/s eta 0:01:09
     ----- --------------------------------- 52.4/400.7 MB 5.1 MB/s eta 0:01:09
     ----- --------------------------------- 53.5/400.7 MB 5.0 MB/s eta 0:01:10
     ----- --------------------------------- 55.3/400.7 MB 5.1 MB/s eta 0:01:08
     ----- --------------------------------- 57.1/400.7 MB 5.1 MB/s eta 0:01:07
     ----- --------------------------------- 59.0/400.7 MB 5.2 MB/s eta 0:01:06
     ----- --------------------------------- 60.8/400.7 MB 5.3 MB/s eta 0:01:05
     ------ -------------------------------- 62.7/400.7 MB 5.4 MB/s eta 0:01:04
     ------ -------------------------------- 64.5/400.7 MB 5.4 MB/s eta 0:01:03
     ------ -------------------------------- 66.3/400.7 MB 5.5 MB/s eta 0:01:02
     ------ -------------------------------- 68.4/400.7 MB 5.5 MB/s eta 0:01:00
     ------ -------------------------------- 70.3/400.7 MB 5.6 MB/s eta 0:01:00
     ------- ------------------------------- 72.1/400.7 MB 5.7 MB/s eta 0:00:59
     ------- ------------------------------- 73.4/400.7 MB 5.7 MB/s eta 0:00:58
     ------- ------------------------------- 73.7/400.7 MB 5.6 MB/s eta 0:00:59
     ------- ------------------------------- 75.0/400.7 MB 5.6 MB/s eta 0:00:59
     ------- ------------------------------- 76.5/400.7 MB 5.6 MB/s eta 0:00:58
     ------- ------------------------------- 78.4/400.7 MB 5.7 MB/s eta 0:00:57
     ------- ------------------------------- 80.2/400.7 MB 5.7 MB/s eta 0:00:56
     ------- ------------------------------- 82.1/400.7 MB 5.8 MB/s eta 0:00:56
     -------- ------------------------------ 83.6/400.7 MB 5.8 MB/s eta 0:00:55
     -------- ------------------------------ 83.9/400.7 MB 5.8 MB/s eta 0:00:55
     -------- ------------------------------ 83.9/400.7 MB 5.8 MB/s eta 0:00:55
     -------- ------------------------------ 84.9/400.7 MB 5.6 MB/s eta 0:00:57
     -------- ------------------------------ 86.5/400.7 MB 5.7 MB/s eta 0:00:56
     -------- ------------------------------ 88.3/400.7 MB 5.7 MB/s eta 0:00:55
     -------- ------------------------------ 90.2/400.7 MB 5.7 MB/s eta 0:00:55
     -------- ------------------------------ 92.0/400.7 MB 5.8 MB/s eta 0:00:54
     --------- ----------------------------- 93.8/400.7 MB 5.8 MB/s eta 0:00:53
     --------- ----------------------------- 95.7/400.7 MB 5.9 MB/s eta 0:00:53
     --------- ----------------------------- 97.5/400.7 MB 5.9 MB/s eta 0:00:52
     --------- ----------------------------- 99.6/400.7 MB 5.9 MB/s eta 0:00:51
     --------- ---------------------------- 101.4/400.7 MB 6.0 MB/s eta 0:00:51
     --------- ---------------------------- 103.5/400.7 MB 6.0 MB/s eta 0:00:50
     --------- ---------------------------- 105.4/400.7 MB 6.1 MB/s eta 0:00:49
     ---------- --------------------------- 107.2/400.7 MB 6.1 MB/s eta 0:00:49
     ---------- --------------------------- 109.1/400.7 MB 6.1 MB/s eta 0:00:48
     ---------- --------------------------- 110.4/400.7 MB 6.1 MB/s eta 0:00:48
     ---------- --------------------------- 111.7/400.7 MB 6.1 MB/s eta 0:00:48
     ---------- --------------------------- 113.2/400.7 MB 6.1 MB/s eta 0:00:47
     ---------- --------------------------- 114.8/400.7 MB 6.2 MB/s eta 0:00:47
     ----------- -------------------------- 116.7/400.7 MB 6.2 MB/s eta 0:00:46
     ----------- -------------------------- 118.8/400.7 MB 6.2 MB/s eta 0:00:46
     ----------- -------------------------- 120.6/400.7 MB 6.3 MB/s eta 0:00:45
     ----------- -------------------------- 122.4/400.7 MB 6.3 MB/s eta 0:00:45
     ----------- -------------------------- 124.5/400.7 MB 6.3 MB/s eta 0:00:44
     ----------- -------------------------- 125.8/400.7 MB 6.3 MB/s eta 0:00:44
     ------------ ------------------------- 126.6/400.7 MB 6.3 MB/s eta 0:00:44
     ------------ ------------------------- 128.2/400.7 MB 6.3 MB/s eta 0:00:44
     ------------ ------------------------- 129.8/400.7 MB 6.3 MB/s eta 0:00:43
     ------------ ------------------------- 131.6/400.7 MB 6.3 MB/s eta 0:00:43
     ------------ ------------------------- 133.4/400.7 MB 6.4 MB/s eta 0:00:42
     ------------ ------------------------- 135.5/400.7 MB 6.4 MB/s eta 0:00:42
     ------------ ------------------------- 136.3/400.7 MB 6.4 MB/s eta 0:00:42
     ------------- ------------------------ 137.4/400.7 MB 6.4 MB/s eta 0:00:42
     ------------- ------------------------ 139.2/400.7 MB 6.4 MB/s eta 0:00:41
     ------------- ------------------------ 140.8/400.7 MB 6.4 MB/s eta 0:00:41
     ------------- ------------------------ 142.6/400.7 MB 6.4 MB/s eta 0:00:41
     ------------- ------------------------ 144.2/400.7 MB 6.4 MB/s eta 0:00:40
     ------------- ------------------------ 145.8/400.7 MB 6.4 MB/s eta 0:00:40
     ------------- ------------------------ 147.6/400.7 MB 6.5 MB/s eta 0:00:40
     -------------- ----------------------- 149.4/400.7 MB 6.5 MB/s eta 0:00:39
     -------------- ----------------------- 151.0/400.7 MB 6.5 MB/s eta 0:00:39
     -------------- ----------------------- 152.8/400.7 MB 6.5 MB/s eta 0:00:39
     -------------- ----------------------- 154.7/400.7 MB 6.5 MB/s eta 0:00:38
     -------------- ----------------------- 156.8/400.7 MB 6.5 MB/s eta 0:00:38
     -------------- ----------------------- 157.3/400.7 MB 6.5 MB/s eta 0:00:38
     -------------- ----------------------- 158.1/400.7 MB 6.5 MB/s eta 0:00:38
     --------------- ---------------------- 159.4/400.7 MB 6.5 MB/s eta 0:00:38
     --------------- ---------------------- 161.2/400.7 MB 6.5 MB/s eta 0:00:37
     --------------- ---------------------- 162.8/400.7 MB 6.5 MB/s eta 0:00:37
     --------------- ---------------------- 164.1/400.7 MB 6.5 MB/s eta 0:00:37
     --------------- ---------------------- 164.9/400.7 MB 6.5 MB/s eta 0:00:37
     --------------- ---------------------- 165.9/400.7 MB 6.5 MB/s eta 0:00:37
     --------------- ---------------------- 167.0/400.7 MB 6.5 MB/s eta 0:00:37
     --------------- ---------------------- 168.0/400.7 MB 6.5 MB/s eta 0:00:37
     ---------------- --------------------- 169.1/400.7 MB 6.4 MB/s eta 0:00:36
     ---------------- --------------------- 170.4/400.7 MB 6.4 MB/s eta 0:00:36
     ---------------- --------------------- 171.4/400.7 MB 6.4 MB/s eta 0:00:36
     ---------------- --------------------- 172.5/400.7 MB 6.4 MB/s eta 0:00:36
     ---------------- --------------------- 173.8/400.7 MB 6.4 MB/s eta 0:00:36
     ---------------- --------------------- 175.1/400.7 MB 6.4 MB/s eta 0:00:36
     ---------------- --------------------- 176.2/400.7 MB 6.4 MB/s eta 0:00:36
     ---------------- --------------------- 177.7/400.7 MB 6.4 MB/s eta 0:00:35
     ----------------- -------------------- 179.6/400.7 MB 6.4 MB/s eta 0:00:35
     ----------------- -------------------- 181.4/400.7 MB 6.4 MB/s eta 0:00:35
     ----------------- -------------------- 183.2/400.7 MB 6.5 MB/s eta 0:00:34
     ----------------- -------------------- 184.8/400.7 MB 6.5 MB/s eta 0:00:34
     ----------------- -------------------- 186.4/400.7 MB 6.5 MB/s eta 0:00:34
     ----------------- -------------------- 188.5/400.7 MB 6.5 MB/s eta 0:00:33
     ------------------ ------------------- 190.1/400.7 MB 6.5 MB/s eta 0:00:33
     ------------------ ------------------- 191.9/400.7 MB 6.5 MB/s eta 0:00:33
     ------------------ ------------------- 193.5/400.7 MB 6.5 MB/s eta 0:00:32
     ------------------ ------------------- 194.8/400.7 MB 6.5 MB/s eta 0:00:32
     ------------------ ------------------- 194.8/400.7 MB 6.5 MB/s eta 0:00:32
     ------------------ ------------------- 195.0/400.7 MB 6.5 MB/s eta 0:00:32
     ------------------ ------------------- 195.3/400.7 MB 6.5 MB/s eta 0:00:32
     ------------------ ------------------- 195.6/400.7 MB 6.4 MB/s eta 0:00:32
     ------------------ ------------------- 196.1/400.7 MB 6.4 MB/s eta 0:00:32
     ------------------ ------------------- 196.6/400.7 MB 6.4 MB/s eta 0:00:33
     ------------------ ------------------- 196.9/400.7 MB 6.4 MB/s eta 0:00:33
     ------------------ ------------------- 197.4/400.7 MB 6.3 MB/s eta 0:00:33
     ------------------ ------------------- 197.7/400.7 MB 6.3 MB/s eta 0:00:33
     ------------------ ------------------- 197.9/400.7 MB 6.3 MB/s eta 0:00:33
     ------------------ ------------------- 198.4/400.7 MB 6.3 MB/s eta 0:00:33
     ------------------ ------------------- 198.7/400.7 MB 6.3 MB/s eta 0:00:33
     ------------------ ------------------- 199.2/400.7 MB 6.2 MB/s eta 0:00:33
     ------------------ ------------------- 199.5/400.7 MB 6.2 MB/s eta 0:00:33
     ------------------ ------------------- 200.0/400.7 MB 6.2 MB/s eta 0:00:33
     ------------------ ------------------- 200.3/400.7 MB 6.2 MB/s eta 0:00:33
     ------------------- ------------------ 200.8/400.7 MB 6.1 MB/s eta 0:00:33
     ------------------- ------------------ 200.8/400.7 MB 6.1 MB/s eta 0:00:33
     ------------------- ------------------ 201.1/400.7 MB 6.1 MB/s eta 0:00:33
     ------------------- ------------------ 201.3/400.7 MB 6.1 MB/s eta 0:00:33
     ------------------- ------------------ 201.9/400.7 MB 6.1 MB/s eta 0:00:33
     ------------------- ------------------ 202.4/400.7 MB 6.1 MB/s eta 0:00:33
     ------------------- ------------------ 203.9/400.7 MB 6.2 MB/s eta 0:00:32
     ------------------- ------------------ 205.3/400.7 MB 6.2 MB/s eta 0:00:32
     ------------------- ------------------ 207.4/400.7 MB 6.3 MB/s eta 0:00:31
     ------------------- ------------------ 208.7/400.7 MB 6.3 MB/s eta 0:00:31
     ------------------- ------------------ 210.2/400.7 MB 6.3 MB/s eta 0:00:31
     -------------------- ----------------- 211.6/400.7 MB 6.4 MB/s eta 0:00:30
     -------------------- ----------------- 213.4/400.7 MB 6.4 MB/s eta 0:00:30
     -------------------- ----------------- 215.0/400.7 MB 6.4 MB/s eta 0:00:29
     -------------------- ----------------- 216.8/400.7 MB 6.5 MB/s eta 0:00:29
     -------------------- ----------------- 218.4/400.7 MB 6.5 MB/s eta 0:00:28
     -------------------- ----------------- 219.9/400.7 MB 6.5 MB/s eta 0:00:28
     -------------------- ----------------- 220.7/400.7 MB 6.5 MB/s eta 0:00:28
     --------------------- ---------------- 222.3/400.7 MB 6.5 MB/s eta 0:00:28
     --------------------- ---------------- 223.9/400.7 MB 6.5 MB/s eta 0:00:28
     --------------------- ---------------- 225.4/400.7 MB 6.5 MB/s eta 0:00:27
     --------------------- ---------------- 227.3/400.7 MB 6.5 MB/s eta 0:00:27
     --------------------- ---------------- 228.9/400.7 MB 6.5 MB/s eta 0:00:27
     --------------------- ---------------- 230.2/400.7 MB 6.5 MB/s eta 0:00:27
     --------------------- ---------------- 231.5/400.7 MB 6.5 MB/s eta 0:00:26
     ---------------------- --------------- 232.8/400.7 MB 6.5 MB/s eta 0:00:26
     ---------------------- --------------- 234.1/400.7 MB 6.5 MB/s eta 0:00:26
     ---------------------- --------------- 235.7/400.7 MB 6.5 MB/s eta 0:00:26
     ---------------------- --------------- 237.0/400.7 MB 6.5 MB/s eta 0:00:26
     ---------------------- --------------- 238.6/400.7 MB 6.5 MB/s eta 0:00:26
     ---------------------- --------------- 240.4/400.7 MB 6.4 MB/s eta 0:00:25
     ---------------------- --------------- 242.0/400.7 MB 6.4 MB/s eta 0:00:25
     ----------------------- -------------- 243.5/400.7 MB 6.4 MB/s eta 0:00:25
     ----------------------- -------------- 245.4/400.7 MB 6.5 MB/s eta 0:00:25
     ----------------------- -------------- 246.9/400.7 MB 6.5 MB/s eta 0:00:24
     ----------------------- -------------- 248.3/400.7 MB 6.5 MB/s eta 0:00:24
     ----------------------- -------------- 249.8/400.7 MB 6.5 MB/s eta 0:00:24
     ----------------------- -------------- 251.4/400.7 MB 6.5 MB/s eta 0:00:24
     ------------------------ ------------- 253.2/400.7 MB 6.5 MB/s eta 0:00:23
     ------------------------ ------------- 255.1/400.7 MB 6.5 MB/s eta 0:00:23
     ------------------------ ------------- 256.9/400.7 MB 6.5 MB/s eta 0:00:23
     ------------------------ ------------- 258.5/400.7 MB 6.5 MB/s eta 0:00:22
     ------------------------ ------------- 260.0/400.7 MB 6.5 MB/s eta 0:00:22
     ------------------------ ------------- 261.9/400.7 MB 6.4 MB/s eta 0:00:22
     ------------------------ ------------- 263.5/400.7 MB 6.4 MB/s eta 0:00:22
     ------------------------- ------------ 265.3/400.7 MB 6.4 MB/s eta 0:00:22
     ------------------------- ------------ 267.1/400.7 MB 6.5 MB/s eta 0:00:21
     ------------------------- ------------ 268.4/400.7 MB 6.5 MB/s eta 0:00:21
     ------------------------- ------------ 270.3/400.7 MB 6.5 MB/s eta 0:00:21
     ------------------------- ------------ 272.1/400.7 MB 6.5 MB/s eta 0:00:20
     ------------------------- ------------ 273.9/400.7 MB 6.5 MB/s eta 0:00:20
     -------------------------- ----------- 275.5/400.7 MB 6.5 MB/s eta 0:00:20
     -------------------------- ----------- 277.1/400.7 MB 6.5 MB/s eta 0:00:20
     -------------------------- ----------- 278.7/400.7 MB 6.5 MB/s eta 0:00:19
     -------------------------- ----------- 280.5/400.7 MB 6.6 MB/s eta 0:00:19
     -------------------------- ----------- 282.3/400.7 MB 6.6 MB/s eta 0:00:18
     -------------------------- ----------- 283.6/400.7 MB 6.6 MB/s eta 0:00:18
     -------------------------- ----------- 284.2/400.7 MB 6.6 MB/s eta 0:00:18
     --------------------------- ---------- 285.0/400.7 MB 6.6 MB/s eta 0:00:18
     --------------------------- ---------- 286.3/400.7 MB 6.5 MB/s eta 0:00:18
     --------------------------- ---------- 287.8/400.7 MB 6.5 MB/s eta 0:00:18
     --------------------------- ---------- 289.4/400.7 MB 6.5 MB/s eta 0:00:18
     --------------------------- ---------- 291.0/400.7 MB 6.5 MB/s eta 0:00:17
     --------------------------- ---------- 292.6/400.7 MB 6.5 MB/s eta 0:00:17
     --------------------------- ---------- 293.9/400.7 MB 6.5 MB/s eta 0:00:17
     ---------------------------- --------- 295.7/400.7 MB 6.5 MB/s eta 0:00:17
     ---------------------------- --------- 297.5/400.7 MB 6.5 MB/s eta 0:00:16
     ---------------------------- --------- 298.8/400.7 MB 6.5 MB/s eta 0:00:16
     ---------------------------- --------- 300.7/400.7 MB 6.5 MB/s eta 0:00:16
     ---------------------------- --------- 302.3/400.7 MB 6.5 MB/s eta 0:00:16
     ---------------------------- --------- 304.1/400.7 MB 6.5 MB/s eta 0:00:15
     ----------------------------- -------- 305.9/400.7 MB 6.5 MB/s eta 0:00:15
     ----------------------------- -------- 307.2/400.7 MB 6.5 MB/s eta 0:00:15
     ----------------------------- -------- 308.8/400.7 MB 6.5 MB/s eta 0:00:15
     ----------------------------- -------- 310.1/400.7 MB 6.5 MB/s eta 0:00:15
     ----------------------------- -------- 311.4/400.7 MB 6.4 MB/s eta 0:00:14
     ----------------------------- -------- 313.0/400.7 MB 6.4 MB/s eta 0:00:14
     ----------------------------- -------- 314.3/400.7 MB 6.4 MB/s eta 0:00:14
     ----------------------------- -------- 315.9/400.7 MB 6.4 MB/s eta 0:00:14
     ------------------------------ ------- 317.5/400.7 MB 6.4 MB/s eta 0:00:13
     ------------------------------ ------- 318.5/400.7 MB 6.4 MB/s eta 0:00:13
     ------------------------------ ------- 319.8/400.7 MB 6.4 MB/s eta 0:00:13
     ------------------------------ ------- 321.1/400.7 MB 6.4 MB/s eta 0:00:13
     ------------------------------ ------- 322.4/400.7 MB 6.4 MB/s eta 0:00:13
     ------------------------------ ------- 324.0/400.7 MB 6.4 MB/s eta 0:00:13
     ------------------------------ ------- 325.1/400.7 MB 6.4 MB/s eta 0:00:12
     ------------------------------ ------- 325.6/400.7 MB 6.3 MB/s eta 0:00:12
     ------------------------------ ------- 326.6/400.7 MB 6.3 MB/s eta 0:00:12

In [43]:
import spacy

nlp = spacy.load("en_core_web_lg")

lst_resp = []

for vaga in descricao_vaga_ingles:
    doc = nlp(vaga)

    entidades = [ent.text for ent in doc.ents if ent.label_ == "ORG"]
    lst_resp.append(entidades)

#transformar a lista de lista em uma lista
lst_resp = [item for sublist in lst_resp for item in sublist]
lst_resp

set_sw_SpacyEN = tratar_lista(lst_resp)
set_sw_SpacyEN

{'AWS',
 'Airflow',
 'Azure',
 'Azure Data Factory',
 'Azure Event Hubs',
 'BI',
 'Business Intelligence',
 'CI',
 'Complete Office',
 'Computer Engineering',
 'Computer Science',
 'Control',
 'Data Analysis',
 'Data Engineering',
 'Data Science for Executive Management',
 'Day Off',
 'DevOps',
 'ELK',
 'ETL',
 'Engineering',
 'Food Voucher',
 'Glue',
 'Grafana',
 'Home Office Assistance',
 'Information Systems',
 'Java',
 'Knowledge of Dynatrace',
 'Knowledge of Java Backend',
 'Mathematics',
 'Meal',
 'Microsoft',
 'NoSQL',
 'OpenTelemetry',
 'Operational Risks',
 'PCP',
 'POWER BI',
 'Pentaho',
 'Planning',
 'Power BI',
 'Python',
 'Referral Awards',
 'SQL',
 'Scala',
 'Science',
 'Spark',
 'Support for Planning',
 'Talend',
 'Teamwork',
 'Technology',
 'Transportation Voucher'}

# Teste 5 - Spacy em Português
### Modelo NLP de Extração de Entidades Nomeadas (NER)

### Na versão em português as entidades estão mal classificadas. A maior parte das entidades que desejo estão classificadas como MISC ou como LOC

In [38]:
#!python -m spacy download pt_core_news_lg

In [128]:
import spacy

nlp = spacy.load("pt_core_news_lg")

lst_resp = []
lst_labes = []

for vaga in descricao_vaga_portugues:
    doc = nlp(vaga)

    entidades = [ent.text for ent in doc.ents if ent.label_ != "ORG"]
    lst_resp.append(entidades)

    labels = [ent.label_ for ent in doc.ents if ent.label_ != "ORG"]
    lst_labes.append(labels)

#juntar em uma única lista
lst_resp = [item for sublist in lst_resp for item in sublist]
lst_labels = [item for sublist in lst_labes for item in sublist]

set_sw_SpacyPT = tratar_lista(lst_resp)

for i in range(len(labels)):
    print(lst_labels[i], lst_resp[i])

LOC Superior
MISC SQL
MISC Python
MISC Power BI
MISC Pentaho
MISC Inglês
LOC Colaborar
MISC BI
MISC Power BI
MISC Tableau
MISC Superior Completo em Ciência da Computação, Engenharia de Dados
MISC Análise de Dados
LOC Sólida
MISC SQL
MISC Conhecimento
MISC Apache NiFi
LOC Talend
LOC Glue
LOC Airflow
MISC SQL Server
MISC PostgreSQL
LOC Familiaridade
MISC BI
MISC Power BI
MISC Tableau
MISC Looker
MISC Python
MISC Go
LOC Gerência Executiva
MISC Riscos Operacionais
MISC Suporte
MISC Riscos Operacionais

# Comparando os Resultados

In [129]:
import regex as re

def tratar_respostas(item):
    item = item.lower()
    item = re.sub(r'^e\s+', '', item)
    item = re.sub(r'\s+e\s+', '', item)
    item = re.sub(r'\s+e$', '', item)
    item = re.sub(r'^ou\s+', '', item)
    item = re.sub(r'\s+ou\s+', '', item)
    item = re.sub(r'\s+ou$', '', item)

    return item

#juntar todos os conjuntos
set_sw = set_sw_TinyBerta.union(set_sw_BertPT).union(set_sw_BertPT_V2).union(set_sw_SpacyEN).union(set_sw_SpacyPT)

#converter todos os valores para minúsculo
set_sw = {item.lower() for item in set_sw}

#converter o conjunto em uma lista
lst_sw_completa = list(set_sw)
lst_sw_completa = [tratar_respostas(item) for item in lst_sw_completa]

In [130]:
df = pd.DataFrame(columns=['Termos','conjunto_verdade','TinyBerta', 'BertPT', 'BertPT_V2', 'SpacyEN', 'SpacyPT'])

df['Termos'] = lst_sw_completa

def checar_resultados(df, conj):
    conj_tratado = [tratar_respostas(item) for item in conj]
    avaliacao = []
    for termo in df['Termos']:
        if termo in conj_tratado:
            avaliacao.append(1)
        else: 
            avaliacao.append(0)
    return avaliacao

df['conjunto_verdade'] = checar_resultados(df, set_verdade)
df['TinyBerta'] = checar_resultados(df, set_sw_TinyBerta)
df['BertPT'] = checar_resultados(df, set_sw_BertPT)
df['BertPT_V2'] = checar_resultados(df, set_sw_BertPT_V2)
df['SpacyEN'] = checar_resultados(df, set_sw_SpacyEN)
df['SpacyPT'] = checar_resultados(df, set_sw_SpacyPT)

df

,Termos,conjunto_verdade,TinyBerta,BertPT,BertPT_V2,SpacyEN,SpacyPT
0,,0,1,0,0,0,0
1,algoritmos,1,0,0,1,0,0
2,scala,1,0,0,0,1,1
3,knowledge of java backend,0,0,0,0,1,0
4,home office assistance,0,0,0,0,1,0
...,...,...,...,...,...,...,...
112,soft skills,0,0,0,1,0,0
113,sckit-learn,0,0,0,1,0,1
114,airflow,1,0,0,0,1,1
115,conhecimentos,0,0,0,0,0,1
116,inglês,0,0,0,0,0,1

In [131]:
#calcular a acurácia
def calcular_acertos(df, coluna_verdade, coluna_calcular):
    total_verdade = df[df[coluna_verdade] == 1].shape[0]
    total_respostas = df[df[coluna_calcular] == 1].shape[0]

    acertos = df[(df[coluna_verdade] == 1) & (df[coluna_calcular] == 1)].shape[0]

    perc_acerto = int(round((acertos / total_respostas) * 100, 0))

    erros = df[(df[coluna_verdade] == 0) & (df[coluna_calcular] == 1)].shape[0]
    perc_erros = int(round((erros / total_respostas) * 100 ,0))

    nao_preditos = df[(df[coluna_verdade] == 1) & (df[coluna_calcular] == 0)].shape[0]
    perc_nao_preditos = int(round((nao_preditos / total_verdade) * 100, 0))

    acuracia = int(round((acertos / total_verdade) * 100, 0))

    return total_respostas, acuracia, perc_acerto, perc_erros, perc_nao_preditos

Scores_TinyBerta = calcular_acertos(df, 'conjunto_verdade', 'TinyBerta')
Scores_BertPT = calcular_acertos(df, 'conjunto_verdade', 'BertPT')
Scores_BertPT_V2 = calcular_acertos(df, 'conjunto_verdade', 'BertPT_V2')
Scores_SpacyEN = calcular_acertos(df, 'conjunto_verdade', 'SpacyEN')
Scores_SpacyPT = calcular_acertos(df, 'conjunto_verdade', 'SpacyPT')

#Adicionar os valores a um novo dataframe
df_scores = pd.DataFrame(columns=['Modelo', 'Total Itens', 'acuracia %', '% Acertos','% Erros', 'Não Preditos'])

df_scores.loc[0] = ['TinyBerta'] + list(Scores_TinyBerta)
df_scores.loc[1] = ['BertPT'] + list(Scores_BertPT)
df_scores.loc[2] = ['BertPT_V2'] + list(Scores_BertPT_V2)
df_scores.loc[3] = ['SpacyEN'] + list(Scores_SpacyEN)
df_scores.loc[4] = ['SpacyPT'] + list(Scores_SpacyPT)
df_scores

      Modelo  Total Itens  acuracia %  % Acertos  % Erros  Não Preditos
0  TinyBerta           12          19         58       42            81
1     BertPT           10          28        100        0            72
2  BertPT_V2           30          42         50       50            58
3    SpacyEN           51          64         45       55            36
4    SpacyPT           70          86         44       56            14